### ISSUE TITLE
Preparar ambiente

### ISSUE THREAD

**Issue by DouglasArS** [atlantico-academy/fake-news-detector#1]
- [x] @DouglasArS 
 - [x] @fiuzatayna 
 - [x] @Jwinny 
 - [x] @SamyaMaria
 - [ ] @eng-robsonsampaio 
 - [ ] @RNy7846

**Comment by omadson** [comment]
@eng-robsonsampaio e @RNy7846, oq falta pra preparação de ambiente?

**Comment by omadson** [comment]
Como não obtive resposta, vou fechar a issue.
